#!/usr/bin/env python3
import subprocess
import json

try:
	from _base_module import BaseModule
except ImportError:
	from ._base_module import BaseModule


class Module(BaseModule):
	def __init__(self):
		super().__init__(argument_spec={
			"name": {"required": False, "type": "str"},
			"image": {"required": False, "type": "str"},
			"auto_remove": {"required": False, "type": "bool", "default": False},
			"state": {
				"required": True,
				"choices": [
					"started", "stopped", "restarted",
					"status", "list", "run"
				]
			}
		})

	def run(self):
		name = self.params.get("name")
		image = self.params.get("image")
		state = self.params.get("state")
		auto_remove = self.params.get("auto_remove")
		changed = False

		# Проверка Docker
		check = subprocess.run(["docker", "info"], capture_output=True, text=True)
		if check.returncode != 0:
			self.fail_json(msg="Docker is not available or not running")

		# LIST
		if state == "list":
			ps = subprocess.run(["docker", "ps", "-a", "--format", "{{json .}}"],
								capture_output=True, text=True)
			lines = ps.stdout.strip().splitlines()
			containers = [json.loads(line) for line in lines] if lines else []
			self.exit_json(changed=False, containers=containers)

		# Для run обязательно нужен image
		if state == "run":
			if not image:
				self.fail_json(msg="'image' is required for state=run")

			# Если имени нет — создаём autogenerated
			if not name:
				name = image.replace(":", "_").replace("/", "_")

			# Проверяем, есть ли контейнер
			exists = subprocess.run(["docker", "inspect", name],
									capture_output=True, text=True)

			if exists.returncode == 0:
				# Контейнер уже есть → просто стартуем
				subprocess.run(["docker", "start", name], capture_output=True)
				self.exit_json(changed=True, msg=f"Existing container {name} started")

			# Pull image если нет
			subprocess.run(["docker", "pull", image], capture_output=True)

			cmd = ["docker", "run", "-d", "--name", name]
			if auto_remove:
				cmd.append("--rm")
			cmd.append(image)

			proc = subprocess.run(cmd, capture_output=True, text=True)

			if proc.returncode != 0:
				self.fail_json(msg=proc.stderr)

			self.exit_json(changed=True, msg=f"Container {name} created and started from {image}")

		# Остальные состояния требуют name
		if not name:
			self.fail_json(msg="Parameter 'name' is required for this state")

		# Проверка существования
		exists = subprocess.run(["docker", "inspect", name],
								capture_output=True, text=True)

		if exists.returncode != 0:
			self.exit_json(changed=False, msg=f"Container {name} not found")

		# Проверка running
		inspect = subprocess.run(["docker", "inspect", "-f", "{{.State.Running}}", name],
								 capture_output=True, text=True)
		running = inspect.stdout.strip() == "true"

		if state == "started":
			if running:
				self.exit_json(changed=False, msg=f"Container {name} already running")
			cmd = ["docker", "start", name]
			changed = True

		elif state == "stopped":
			if not running:
				self.exit_json(changed=False, msg=f"Container {name} already stopped")
			cmd = ["docker", "stop", name]
			changed = True

		elif state == "restarted":
			cmd = ["docker", "restart", name]
			changed = True

		elif state == "status":
			self.exit_json(changed=False, container=name, running=running)

		proc = subprocess.run(cmd, capture_output=True, text=True)
		if proc.returncode != 0:
			self.fail_json(msg=proc.stderr)

		self.exit_json(changed=changed, msg=f"Container {name} {state}")


if __name__ == "__main__":
	Module().run()
